[
  {
    "instruction": "高亮显示${excel_path}中${materials}材质的组件。",
    "input": "输入：\nexcel_path：${excel_path}\n materials：${materials}",
    "output": "以下是不可分割的完整代码:\n\n```Language=CATSCRIPT\nSub CATMain()\n        Dim ePh\n        ePh = \"${excel_path}\"\n        Dim mtls\n        mtls = \"${materials}\"\n        \n        Dim fso As Object\n        Set fso = CreateObject(\"Scripting.FileSystemObject\")\n        If fso.FileExists(ePh) = False Then\n            ePh = InputBox(\"Excel not Exists, enter excel path: \", \"Enter Excel path: \", ePh)\n            If fso.FileExists(ePh) = False Then\n                    MsgBox \"Excel not Exists: \" & ePh\n                    Exit Sub\n            End If\n        End If\n        Dim partNumberTitle\n        partNumberTitle = \"Part number\"\n        Dim mapSearch\n        Set mapSearch = CreateObject(\"Scripting.Dictionary\")\n        Dim ret As Integer\n        ret = SplitStr(mtls, \",\", mapSearch)\n        Dim showPartNumber As Object\n        Set showPartNumber = CreateObject(\"Scripting.Dictionary\")\n        ReadExcel showPartNumber, mapSearch, ePh, partNumberTitle\n        Dim showChildComps As Object\n        Set showChildComps = CreateObject(\"System.Collections.ArrayList\")\n        Dim tspyChildComps As Object\n        Set tspyChildComps = CreateObject(\"System.Collections.ArrayList\")\n        Dim rootDoc As ProductDocument\n        Set rootDoc = CATIA.ActiveDocument\n        If rootDoc Is Nothing Then\n            Exit Sub\n        End If\n        If TypeName(rootDoc) <> \"ProductDocument\" Then\n            Exit Sub\n        End If\n        Dim rProduct As Product\n        Set rProduct = rootDoc.Product\n        Dim productChildren As Products\n        Set productChildren = rProduct.Products\n        ret = GetChildren(rProduct, rProduct, partNames, showChildComps, tspyChildComps, False)\n        ret = ChangeCompState(rProduct, showChildComps, 0, -1)\n        ret = ChangeCompState(rProduct, tspyChildComps, -1, 0)\nEnd Sub```"
  },
  {
    "instruction": "高亮显示${materials}材质的组件, part number表格路径${excel_path}。",
    "input": "",
    "output": ""
  }
]
